Repository 1313BAN/team12-Tlog-FE, pull requests merged in 2025-05, with the labels that each got.

#11 [FEAT] 공통 레이아웃 설정 및 인증 상태 관리 코드 작성
  src/assets/alarm.svg
  src/assets/logo.png
  src/assets/logo.svg
  src/assets/noti.svg
  src/components/common/CommonHeader.vue
  src/components/common/index.ts
  src/global.css
  src/layouts/DefaultLayout.vue
  src/router/index.ts
  src/services/api/api.ts
  src/services/api/index.ts
  src/services/api/interceptors.ts
  src/services/api/types.ts
  src/stores/auth.ts
  src/views/HomeView.vue
  src/views/LoginView.vue
  src/views/MainView.vue
  src/views/PlanList.vue
  src/views/RecordList.vue
  src/views/SignupView.vue
Labels: 🎨 Html&css, ✨ Feature

#14 [FEAT] 구글 소셜 로그인 기능 구현
  index.html
  package-lock.json
  package.json
  src/assets/my.svg
  src/components/common/CommonHeader.vue
  src/main.ts
  src/router/index.ts
  src/services/api/api.ts
  src/stores/auth.ts
  src/types/global.d.ts
  src/types/pinia-plugin-persistedstate.d.ts
  src/views/LoginView.vue
  src/views/MyPage.vue
  src/views/SignupView.vue
  tsconfig.json
Labels: 📬 API, ✨ Feature

#15 [FEAT] 로그인 및 회원가입 UI 적용
  src/assets/google-icon.svg
  src/assets/kakao-icon.svg
  src/composables/user/index.ts
  src/composables/user/useNicknameCheck.ts
  src/types/global.d.ts
  src/views/LoginView.vue
  src/views/SignupView.vue
Labels: 🎨 Html&css, ✨ Feature

#21 [Feat] 홈페이지 구현
  src/components/views/home/CitySelector.vue
  src/components/views/home/FeatureCard.vue
  src/components/views/home/FeaturePreview.vue
  src/components/views/home/FeaturesSection.vue
  src/components/views/home/HeroSection.vue
  src/components/views/recordDetail/AiStoryAccordion.vue
  src/components/views/recordDetail/TripPlanAccordion.vue
  src/components/views/recordDetail/TripRecordCard.vue
  src/layouts/DefaultLayout.vue
  src/router/index.ts
  src/views/HomeView.vue
  src/views/RecordDetail.vue
  src/views/RecordList.vue
Labels: 📬 API, ✨ Feature

#23 [FEAT] 경로 그리기 기능 및 장소 draggable 적용 + polyline 중복 관련 트러블슈팅
  package-lock.json
  package.json
  src/components/plan/Step3AccommodationSetting.vue
  src/components/plan/Step4PlaceSearch.vue
  src/composables/plan/usePlanMap.ts
  src/router/index.ts
  src/views/PlanView.vue
Labels: ✨ Feature

#26 [FEAT] 계획 생성 api 연동
  src/components/plan/CustomStepper.vue
  src/constants/cityMapConfig.ts
  src/services/api/index.ts
  src/services/api/tripPlan.ts
  src/stores/plan.ts
  src/views/PlanView.vue
Labels: 📬 API, ✨ Feature

#31 [FEAT] 계획 디테일페이지 구현
  src/components/plan/CustomStepper.vue
  src/components/plan/Step1DateSetting.vue
  src/components/ui/badge/Badge.vue
  src/components/ui/badge/index.ts
  src/components/ui/resizable/ResizableHandle.vue
  src/components/ui/resizable/ResizablePanel.vue
  src/components/ui/resizable/ResizablePanelGroup.vue
  src/components/ui/resizable/index.ts
  src/components/ui/separator/Separator.vue
  src/components/ui/separator/index.ts
  src/constants/cityMapConfig.ts
  src/constants/index.ts
  src/router/index.ts
  src/views/PlanDetail.vue
  src/views/PlanList.vue
Labels: 🎨 Html&css, ✨ Feature

#33 [FEAT] 헬퍼함수 추출
  src/views/PlanDetail.vue
Labels: 🔨 Refactor

#39 [FEAT] 친구초대 api 연동
  src/components/plan/Step2FriendInvite.vue
  src/services/api/index.ts
  src/services/api/userApi.ts
  src/stores/plan.ts
  src/views/PlanEditView.vue
Labels: 📬 API, ✨ Feature

#40 [FEAT] 헤더 UI 추가
  src/components/common/CommonHeader.vue
  src/components/views/home/FeaturesSection.vue
Labels: 🎨 Html&css

#42 [FEAT] 계획 편집페이지 락 적용
  src/composables/plan/index.ts
  src/composables/plan/useEditLock.ts
  src/services/api/editLock.ts
  src/services/api/index.ts
  src/services/api/tripService.ts
  src/views/PlanDetail.vue
  src/views/PlanEditView.vue
Labels: 📬 API, ✨ Feature

#44 [Feat] 여행 삭제 버튼 추가
  src/components/ui/alert-dialog/AlertDialog.vue
  src/components/ui/alert-dialog/AlertDialogAction.vue
  src/components/ui/alert-dialog/AlertDialogCancel.vue
  src/components/ui/alert-dialog/AlertDialogContent.vue
  src/components/ui/alert-dialog/AlertDialogDescription.vue
  src/components/ui/alert-dialog/AlertDialogFooter.vue
  src/components/ui/alert-dialog/AlertDialogHeader.vue
  src/components/ui/alert-dialog/AlertDialogTitle.vue
  src/components/ui/alert-dialog/AlertDialogTrigger.vue
  src/components/ui/alert-dialog/index.ts
  src/components/views/recordList/TripStorySection.vue
  src/views/RecordList.vue
Labels: 📬 API, ✨ Feature

#47 [FIX] 빌드 에러 해결
  src/components/ui/command/Command.vue
  src/components/views/home/CitySelector.vue
  src/components/views/home/HeroSection.vue
  src/components/views/recordDetail/AiStoryContent.vue
  src/components/views/recordDetail/AiStoryEmpty.vue
  src/components/views/recordDetail/AiStoryHeader.vue
  src/components/views/recordList/TripStorySection.vue
  src/composables/plan/usePlanMap.ts
  src/router/index.ts
  src/views/MyPage.vue
  src/views/PlanList.vue
  src/views/RecordList.vue
Labels: 🌏 Deploy

#49 [FEAT] 빌드 에러 해결
  src/views/PlanEditView.vue
  src/views/PlanView.vue
  src/views/RecordDetail.vue
Labels: 🌏 Deploy
